#!/bin/bash
# Configuration inspired by https://github.com/Bisa/factorio-init

# The absolute path to the factorio directory
FACTORIO_PATH=/opt/factorio
# The absolute path to the factorio binary
BINARY=${FACTORIO_PATH}/bin/x64/factorio

# The latency expected between peers (milliseconds)
# Try to set this to the highest latency + 30
# If Peer A and B have a latency of 100 between each other
# set this to 130
LATENCY=250

# The number of minutes between each autosave
AUTOSAVE_INTERVAL=10
# The number of autosaves to use for rotation
AUTOSAVE_SLOTS=3

# Extras
# Additional binary arguments, these will be sent to the binary when issuing the "start" command
EXTRA_BINARGS="--disallow-commands"
#EXTRA_BINARGS="--disallow-commands --peer-to-peer"

#
# Refrain from changing the variables below, they are used internally by the script and should
# not be altered unless you know what you are doing
#
SAVE_NAME=factorio-init-save
INVOCATION="${BINARY} --start-server ${SAVE_NAME} --autosave-interval ${AUTOSAVE_INTERVAL} --autosave-slots ${AUTOSAVE_SLOTS} --latency-ms ${LATENCY} ${EXTRA_BINARGS}"
